### PR TITLE
BET-1211: Build both for linux/amd64 and linux/arm64 (actually Apple M1)

### PR DESCRIPTION
**Pull request by erszcz**

### CODE REVIEW

**Review by gilacost — APPROVED** [review]
LGTPep! 🚀

**Comment by erszcz** [comment]
Merging opportunistically - please let me know anyway if you have any comments @jamesza @rodrigues @gilacost.

**Comment by gilacost** [comment]
*Note to self:* we need to automate the branch deletion after merge

**Comment by gilacost** [comment]
I am really keen to use official image instead, will be tackled in CI 😛

**Pull request merged**
